Add Shortcuts
karasevm/PrivateDNSAndroid pull request #37
Opened 2024-10-17 18:23 UTC by InfiniteCoder06

Links with #35

2024-10-24 09:24 UTC, karasevm requested changes
I also have a general question on the way the shortcuts are supposed to work. From reading the code I understand that neither shortcuts modify the provider, the toggle one switches from any other mode to off and then to the first enabled in the app, the switch just toggles through the enabled modes but also to off if a provider is set. Am I correct? Could you please provide an example for each one, as I'm not sure why we need both?

2024-10-24 09:24 UTC, karasevm commented on app/src/main/res/xml/shortcuts.xml
> +            android:data="myapp://switch_mode"/>
The placeholder `myapp://` scheme should be replaced with with `privatednstoggle://` as that seems to be the common practice.

2024-10-24 09:24 UTC, karasevm commented on app/src/main/java/ru/karasevm/privatednstoggle/service/ShortcutService.kt
> +                        PrivateDNSUtils.setPrivateMode(contentResolver, DNS_MODE_OFF)
Any reason for not using `setDnsModeAndShowToast()` here?

2024-10-24 09:24 UTC, karasevm commented on app/src/main/java/ru/karasevm/privatednstoggle/service/ShortcutService.kt
> +        PrivateDNSUtils.setPrivateMode(contentResolver, dnsMode)
Don't set the mode to `hostname` without setting a provider or at least checking that one is set. This is undefined behavior in android, leaves the user without working DNS, and causes the app itself to crash.

2024-10-30 05:49 UTC, InfiniteCoder06 commented
> the toggle one switches from any other mode to off

Exactly



> switch just toggles through the enabled modes but also to off if a provider is set

Yeah, Overlooked it, The Actual Usecase is just to switch Private Providers only and not Off or Auto

Since It is used by Automation apps it will be difficult if we merge them to implement in that hence i split them

2024-11-05 12:20 UTC, karasevm commented
If by "switch Private Providers only" you mean cycle through the added providers, it still doesn't do that as it never actually does anything with the next provider. In practice I still get `Off (if enabled) -> Auto (if enabled) -> existing provider/dns.google`.

2024-11-23 06:33 UTC, InfiniteCoder06 commented
I am lil busy will be working later....

2025-01-13 11:45 UTC, ataraxia-admail commented
Hi, when will this feature be implemented, its Jan 2025, i wish that we can push this change asap to enable automations with it

2025-02-03 18:41 UTC, saltsoftdrink commented
@karasevm @papaindiatango it's been Feb 4 when will be the feature added 😭

2025-02-09 10:29 UTC, InfiniteCoder06 commented
@karasevm Ready for Review

2025-02-19 13:04 UTC, karasevm requested changes
Main issues:
- You've rebased this PR on main, but in the process reverted a lot of changes done in 4f6dc13 (maybe also other commits), please fix this.
- A `meta-data` element is required in the manifest for the shortcuts to appear, as is the shortcuts don't appear at all.

I'd also like to add multiple other shortcuts for automation, but let's get this working and merged first.

2025-02-19 13:04 UTC, karasevm commented on app/src/main/java/ru/karasevm/privatednstoggle/service/ShortcutService.kt
> +        val text = when (dnsMode) {
Please don't hardcode strings. We have `set_to_off_toast`, `set_to_auto_toast`, and `set_to_provider_toast` already.

2025-03-03 17:33 UTC, InfiniteCoder06 commented
Little busy with studies will be done by month end

2025-03-14 09:17 UTC, andrei-a-papou commented
> Hi, when will this feature be implemented, its Jan 2025, i really want this feature to be added asap to enable automations with it, thanks for working on it

@saltsoftdrink @ataraxia-admail 

This is open source, the author doesn't owes you nothing. He probably has other things to do such as working elsewhere to pay the bills or feeding his family.

If you need something ASAP, have you considered paying for it or contributing in any other meaningful way? If you can't, at least stop making demands with crying emoji :D How old are you, for crying out loud. It's just childish :D

2025-03-15 09:15 UTC, saltsoftdrink commented
> > Hi, when will this feature be implemented, its Jan 2025, i really want this feature to be added asap to enable automations with it, thanks for working on it
> 
> @saltsoftdrink @ataraxia-admail
> 
> This is open source, the author owes you nothing. He probably has other things to do such as working elsewhere to pay the bills or feeding his family.
> 
> If you need something ASAP, have you considered paying for it or contributing in any other meaningful way? If you can't, at least stop making demands with crying emoji :D How old are you, for crying out loud. It's just childish :D

😂

2025-07-04 15:17 UTC, karasevm commented
I've merged this manually and will finish the implementation in the next update. Thanks for your contribution.

2025-07-04 15:17 UTC, closed without merging